kind: pipeline
type: kubernetes
name: build and test

steps:
  - name: lock-requirements
    image: python:3.8
    commands:
      - pip install pipenv
      - pipenv lock --keep-outdated --requirements > requirements.txt
      - pipenv lock --keep-outdated --requirements --dev-only > requirements-dev.txt

  - name: test
    image: python:3.8
    environment:
      REDIS_HOST: "redis"
    commands:
      - pip install -r requirements.txt
      - pip install -r requirements-dev.txt
      - python manage.py test
    depends_on:
    - lock-requirements