# Generated by Django 2.0.5 on 2018-09-25 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='seed',
            field=models.IntegerField(default=999),
        ),
    ]
