# Generated by Django 2.0.7 on 2018-10-01 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_entry_seed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deseed',
            options={'ordering': ['seed']},
        ),
        migrations.AlterUniqueTogether(
            name='deseed',
            unique_together={('entry', 'de')},
        ),
    ]
