# Generated by Django 3.2.2 on 2021-05-15 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20181006_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='contactNumber',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
